server:
  port: 8080

spring:
  application:
    name: insurances

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: info
    '[org.springframework.web]': debug