server:
  port: 8080

application:
  jwt:
    key: 1nsur4nc3520250127212200ExampleForTest
  security:
    client:
      pwd: dummypass

spring:
  datasource:
      url: jdbc:postgresql://postgres:5432/postgres
      username: postgres
      password: 2449
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        show-sql: true
        open-in-view: true
  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      data-locations:
      - classpath*: data.sql

logging:
  level:
    root: info
    '[org.springframework.web]': debug
    '[org.hibernate.SQL]': debug