server:
  port: 8080

spring:
  application:
    name: insurances
  main:
    allow-circular-references: true
  profiles:
    active:
    - dev
  mvc:
    servlet:
      path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html